url: https://fr3nch4.github.io
baseurl: /Fr3nch4Sec/

# Site settings
title: fr3nch4 - Portfolio
email: cyoann30@gmail.com
description: "This is my static Portfolio, and i add things when i have time."



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Dijon, 21000
  - line: France

# Build settings
markdown: kramdown
permalink: pretty