baseurl: ""
url: "https://fr3nch4.github.io"
theme: "agency-jekyll-theme"
title: "fr3nch4 - Portfolio"
email: cyoann30@gmail.com
description: "This is my static Portfolio, and i add things when i have time."
social:
  - title: twitter
    url: # Ajoutez votre URL Twitter ou laissez vide
  - title: facebook
    url: # Ajoutez votre URL Facebook ou laissez vide
  - title: stack-overflow
    url: # Ajoutez votre URL Stack Overflow ou laissez vide
  - title: bitbucket
    url: # Ajoutez votre URL Bitbucket ou laissez vide
  - title: github
    url: https://github.com/Fr3nch4Sec
address:
  - line: Dijon, 21000
  - line: France
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _sass
  style: compressed
